### ISSUE TITLE
Ethernet Segment sizing

### ISSUE THREAD

**Issue by pedro-ricardo** [eclipse-4diac/4diac-ide#271]
On the "System Configuration" perspective I find it cool that it is possible to resize the length of the Ethernet segment but the **initial size** of it is **too small** on the nightly build of 2024-07-11.

Here is a picture to illustrate it
![eth](https://github.com/eclipse-4diac/4diac-ide/assets/15893711/11dff1ce-d826-4511-b33c-7693fcd3e2bb)

When it is this small upon just drag and dropped, it feels like a bug, even though it works normally.

**Comment by azoitl** [comment]
@pedro-ricardo can you please verify in tomorrows nightly build?

**Comment by pedro-ricardo** [comment]
Sure thing.

**Comment by pedro-ricardo** [comment]
Confirmed Fixed
