### ISSUE TITLE
Test hiccup

### ISSUE THREAD

**Issue by TTTYYTTTT0** [eclipse-4diac/4diac-ide#333]
Hello author, the latest version runs the example, there is no way to open the runtime autonomously.

**Comment by MartinMelikMerkumians** [comment]
Hi,

please add more details and a screenshot of your issue. I don't understand your problem

**Comment by TTTYYTTTT0** [comment]
![3417261B-0BD4-43fe-8F36-1658320B3D27](https://github.com/user-attachments/assets/69556fac-593f-493c-901c-202147cdadce)
![A10CDC96-D6A4-47cd-B2F6-EC0A179FE43D](https://github.com/user-attachments/assets/bff0ac87-8447-4d32-af52-47ae515dc073)
The latest develop branch source code does not find the original port emulation after running

**Comment by MartinMelikMerkumians** [comment]
Did you start a 4diac-FORTE prior to trying to deploy your application?

**Comment by TTTYYTTTT0** [comment]
I thought you removed the feature option and did automatic configuration.
Without port simulation, if multiple ports are involved, do you need port simulation software?

**Comment by TTTYYTTTT0** [comment]
![1](https://github.com/user-attachments/assets/3e27f8cb-01d4-47dd-808b-9151bf26df9e)
I thought it was configured so don't need a human click

**Comment by azoitl** [comment]
Unfortunately we are not doing automatically. If you go to Run -> run configurations you can configure the 4diac FORTE instances and their port you would like to run. These run configurations you can conveniently be started through the run menu. You can even combine that in a set of run configurations.

**Comment by TTTYYTTTT0** [comment]
Okay, thank you very much.

**Comment by TTTYYTTTT0** [comment]
Excuse me, I want to ask if the source code of your version 1.12.2 is open source, I can't find it

**Comment by azoitl** [comment]
For completeness and documentation yes all 4diac IDE versions are available in source. Since versions 1.9.0 you can find them tagged in this github repository. For older versions please have a look at the branches and tags in our previous Mercurial repository hosted at SourceForge: https://sourceforge.net/p/fordiac/fordiac-ide/ci/default/tree/
