### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by TTTYYTTTT0** [eclipse-4diac/4diac-ide#354]
How to change the language to Chinese

**Comment by TTTYYTTTT0** [comment]
Please help me, thank you

**Comment by azoitl** [comment]
Currently 4diac IDE only comes in English. We have prepared most places to be translate able and if you search in our forum you can find people that tried to translate 4diac IDE to different languages. But sofar this translations have not yet been contributed back. If you want to translate 4diac IDE I'm happy to support you.

**Comment by TTTYYTTTT0** [comment]
Before, I opened each file and translated it manually, and it worked just fine
