### ISSUE TITLE
F_MOVE cannot be configured in a Typed Subapp

### ISSUE THREAD

**Issue by franz-hoepfinger-4diac** [eclipse-4diac/4diac-ide#461]
Hi, 

F_MOVE cannot be configured in a Typed Subapp, 
while in Ressource it works. 

also working is modify the XML of the Subapp. 

Thanks,

**Comment by franz-hoepfinger-4diac** [comment]
in Typed Subapp:
![image](https://github.com/user-attachments/assets/f1cd5e67-44ec-4e9f-b37f-0574d0f47adc)

**Comment by franz-hoepfinger-4diac** [comment]
in Resource:
![image](https://github.com/user-attachments/assets/4d7b655b-be02-4a8e-8890-2f43ef6a87e3)

**Comment by franz-hoepfinger-4diac** [comment]
tested in 
4diac-ide_3.0.0-win32.win32.x86_64_nightly_2024-09-29_0545
still broken in Typed Subapp.

**Comment by bwiesmayr** [comment]
https://github.com/eclipse-4diac/4diac-ide/pull/627 this should fix it

**Comment by franz-hoepfinger-4diac** [comment]
FIXED
tested in 4diac-ide_3.0.0-win32.win32.x86_64_nightly_2024-10-18_0544
