### ISSUE TITLE
adapters in FBs are shown in lower case

### ISSUE THREAD

**Issue by moniwe** [eclipse-4diac/4diac-ide#489]
using 4diac-ide Version: 3.0.0 Build id: 2024-09-14_0544 shows adapters in lower case within the interface, selecting there within the drop down also shows it in lower case:
![grafik](https://github.com/user-attachments/assets/5f8cfc77-28a0-41af-aa8e-90d5b3b5b190)

when entering it manually within the tabbed properties it accepts the capital letters:
![grafik](https://github.com/user-attachments/assets/344fa439-69b0-4008-9a99-876767f84af2)

it seems that it became an issue due to package name changes.

**Comment by mx990** [comment]
Thank you for the hint about the package name change. This enabled me to reproduce the problem. The name of the created error type entry used the lowercase name instead of the original name. I have created a PR https://github.com/eclipse-4diac/4diac-ide/pull/512 to fix the problem.

**Comment by moniwe** [comment]
thanx
