### ISSUE TITLE
can't select "1" as ECC Transition condition

### ISSUE THREAD

**Issue by WinterMelanie** [eclipse-4diac/4diac-ide#52]
When creating a new transition the condition is "1", but one can't choose "1" again, after having choosen a different condition. It will revert itself to the [none] condition.

**Comment by bwiesmayr** [comment]
<img width="119" alt="image" src="https://github.com/eclipse-4diac/4diac-ide/assets/65956373/5ee08acd-6c2c-4ed7-bc49-62715cb8e58c">
I did some debugging and can reproduce the problem. It seems like the command is executed / 1 is set, but there is a problem with the drawing
