### ISSUE TITLE
Remove Ctrl+click Jump to type HpyerLink

### ISSUE THREAD

**Issue by azoitl** [eclipse-4diac/4diac-ide#55]
For a long time we had the feature that while pressing ctrl and clicking on an FB Type name or clicking on a plug or socket that the according type editor is opened. While this is a nice feature to quickly navigate to a type it has several problems:

- It leads to strange behavior when using the ctrl key to select several FBs
- For plugs and sockets it is not possible to create connections with the ctrl+click feature
- User feedback (i.e., showing link underline on type names) is not really always working

As I find the first two options rather important I would propose to remove this feature. 

We have as one solution the `Open type in  editor` context menu entry that provides this feature. I would propose to add this feature also to the `Navigate` main menu. With that the feature is IMHO more discoverable and at the same time does not lead to inconsistent behavior.

@bwiesmayr @moniwe  how you see that.

@jwalt thx for bringing this to my attention and triggering this idea.

**Comment by bwiesmayr** [comment]
I agree that the feature lately does not work so well. However, I would like to point out that the "open type in editor" was lately broken for adapters. It does not appear in the context menu and also the pin property sheet lost the button. Not sure how and when this happened, but in combination with your proposed change, it is very annoying

**Comment by azoitl** [comment]
> I agree that the feature lately does not work so well. However, I would like to point out that the "open type in editor" was lately broken for adapters. It does not appear in the context menu and also the pin property sheet lost the button. Not sure how and when this happened, but in combination with your proposed change, it is very annoying

I was not aware about that. Yes this feature needs to come back.

**Comment by pedro-ricardo** [comment]
I can confirm that going into the type editor while selecting multiple blocks happens too often with me... removing this from Ctrl+Click and keeping a working option in the context menu sounds nice.

**Comment by azoitl** [comment]
With PR#93 the base work for opening types from the context menu is done. If approved the next step would be to remove the ctrl click.
