### ISSUE TITLE
Cannot Save Application when Adaptor is at Subapplication Interface

### ISSUE THREAD

**Issue by sstuklde2020** [eclipse-4diac/4diac-ide#793]
![Issue1_SaveNotAllowed](https://github.com/user-attachments/assets/01e6e288-5f73-477c-8db6-3215eb798e3d)

I cannot save the application, if the adaptor is present at Subapplication interface.

![Issue1_SaveDoneWhenUnexpaded](https://github.com/user-attachments/assets/873d1990-e05f-4ec3-bf34-3645eff9e693)

If i flatten the subapplication, then saving is allowed.

The following error occurs and the Details are in the file at bottom: 
![Issue1_Error](https://github.com/user-attachments/assets/30837518-5066-4f16-b8cb-d1fd8c31e781)

[Issue1.txt](https://github.com/user-attachments/files/17935780/Issue1.txt)

**Comment by azoitl** [comment]
The root case of this issue is the same as #764 and fixed with #795.
