### ISSUE TITLE
Adapter Save Issue on Subapplication Interface and Major Error Occured

### ISSUE THREAD

**Issue by sstuklde2020** [eclipse-4diac/4diac-ide#794]
I cannot save application, if i have adapter at subapplication interface as shown in the image
![Issue2_SaveError](https://github.com/user-attachments/assets/9ac441a0-5b86-49da-ba69-6b6334dbeaae)

[Issue1.txt](https://github.com/user-attachments/files/17935983/Issue1.txt)

Additionally, If i click on the adapter interface, following Major Error occurs. 
The details are in the file at bottom.
![Issue2_SaveNotAllowedMajorErrorThrown](https://github.com/user-attachments/assets/c9153dfa-3c3d-4720-a930-02695e4c8b21)

[Issue2.txt](https://github.com/user-attachments/files/17935912/Issue2.txt)

**Comment by azoitl** [comment]
Many thanks for reporting this issue. Fixed in the freeze branch.
