### ISSUE TITLE
Auto and Connection Layouting visible in all context menus

### ISSUE THREAD

**Issue by mx990** [eclipse-4diac/4diac-ide#796]
The *Auto Layouting* and *Connection Layouting* entries are visible in all context menus when nothing is selected, see the screenshot below for an example:

![image](https://github.com/user-attachments/assets/a8ed0244-9551-4bd7-9bce-986cd3def4c6)

This behavior has been observed on current develop.

**Comment by azoitl** [comment]
I think this is a duplicated of #748

**Comment by mx990** [comment]
I originally thought this was a different problem since it also happens in completely unrelated views.

Closed as duplicate of https://github.com/eclipse-4diac/4diac-ide/issues/748
