### ISSUE TITLE
Strange Eclipse build error messages in develop branch

### ISSUE THREAD

**Issue by melekhove** [eclipse-4diac/4diac-ide#802]
It's not exactly a bug in application, but it's real inconvenience. The strange thing is that maven builds project without any problem while Eclipse reports bugs.

Steps to reproduce:
- clone fresh copy of the repository `git clone --single-branch --branch develop https://github.com/eclipse-4diac/4diac-ide.git 4diac-ide-test`
- start Eclipse with fresh new workspace `eclipse -data workspace-test -showlocation`
- set the Api Baseline as described in [Building and Running 4diac IDE](https://github.com/eclipse-4diac/4diac-documentation/blob/main/src/development/building4diac.adoc#13-import-plug-ins-into-workspace)
- import "Projects from Folder or Archive"
- wait for build to finish

Observe the following errors:
```
| Description                                                                                                           | Resource          | Location | Type            |
|-----------------------------------------------------------------------------------------------------------------------|-------------------|----------|-----------------|
| Cannot create type for STAlgorithm because its EPackage is unknown.                                                   | STAlgorithm.xtext | line 27  | Grammar Problem |
| Cannot create type for STAlgorithmBody because its EPackage is unknown.                                               | STAlgorithm.xtext | line 32  | Grammar Problem |
| Cannot create type for STFunction because its EPackage is unknown.                                                    | STFunction.xtext  | line 33  | Grammar Problem |
| Cannot create type for STMethod because its EPackage is unknown.                                                      | STAlgorithm.xtext | line 37  | Grammar Problem |
| Cannot create type for STMethodBody because its EPackage is unknown.                                                  | STAlgorithm.xtext | line 42  | Grammar Problem |
| Couldn't resolve reference to EClassifier 'STAlgorithmBody'.                                                          | STAlgorithm.xtext | line 33  | Grammar Problem |
| Couldn't resolve reference to EClassifier 'STAlgorithmSource'.                                                        | STAlgorithm.xtext | line 22  | Grammar Problem |
| Couldn't resolve reference to EClassifier 'STAlgorithmSourceElement'.                                                 | STAlgorithm.xtext | line 24  | Grammar Problem |
| Couldn't resolve reference to EClassifier 'STFunction'.                                                               | STFunction.xtext  | line 34  | Grammar Problem |
| Couldn't resolve reference to EClassifier 'STFunctionSource'.                                                         | STFunction.xtext  | line 28  | Grammar Problem |
| Couldn't resolve reference to EClassifier 'STMethodBody'.                                                             | STAlgorithm.xtext | line 43  | Grammar Problem |
| Couldn't resolve reference to EPackage '<http://www.eclipse.org/fordiac/ide/structuredtextalgorithm/STAlgorithm'.     | STAlgorithm.xtext | line> 15 | Grammar Problem |
| Couldn't resolve reference to EPackage '<http://www.eclipse.org/fordiac/ide/structuredtextfunctioneditor/STFunction'. | STFunction.xtext  | line> 20 | Grammar Problem |
```
Multiple clean & rebuild don't help, though maven builds all targets without any problems.
But if you check out previous version, like this for example:

```
git checkout f4ede2441bd91bf0
HEAD is now at f4ede2441 Divided Update Changes into separate rename/delete changes
```
and then update project in Eclipse, clean and rebuild it, then issues will be gone and then you can switch back to develop branch, clean project and errors won't appear again.

After some experiments I discovered that impossibility to build project from fresh checkout in fresh workspace first appeared in commit c6aa8214dbc24850881573833f5a253ec0c1d133
Before that commit Ecipse builds fresh project without problems, after that commit it fails.

My guess is that it might be related to the following changes:
- [plugins/org.eclipse.fordiac.ide.structuredtextalgorithm.model/.classpath](https://github.com/eclipse-4diac/4diac-ide/commit/c6aa8214dbc24850881573833f5a253ec0c1d133#diff-564a42adbabdfd08595e008951a91fc13187924ec15b608942267db1219e8cf7L4)
- [plugins/org.eclipse.fordiac.ide.structuredtextalgorithm.model/.project](https://github.com/eclipse-4diac/4diac-ide/commit/c6aa8214dbc24850881573833f5a253ec0c1d133#diff-e2cb0719b67e985dedd749f7409dd34aaf6db72b86e398b2ae1420d86016ac02L8)

but I'm not sure.
Could someone with more knowledge of the project structure please take a look ?

Thanks!

**Comment by mx990** [comment]
Thank you for reporting this problem. The detailed description was really helpful!
